[project]
name = "verifiers"
authors = [
    {name = "William Brown", email = "williambrown97@gmail.com"},
]
version = "0.1.1"
description = "Verifiers for reinforcement learning with LLMs"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11,<3.13"
keywords = ["reinforcement-learning", "llm", "rl", "grpo", "verifiable-environments", "multi-turn"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "openai",
    "datasets",
]

[project.optional-dependencies]
all = [
    "requests",
    "torch>=2.7.0",
    "transformers",
    "accelerate>=1.4.0",
    "peft",
    "wandb",
    "rich",
    "trl>=0.17.0",
    "vllm>=0.9.1",
    "liger-kernel>=0.5.10",
    "deepspeed",
    "nest-asyncio>=1.6.0",
    "ipykernel",
    "ipywidgets",
    "duckduckgo-search",
    "brave-search",
    "reasoning-gym",
    "smolagents>=1.15.0",
    "textarena",
    "nltk",
    "tau-bench @ git+https://github.com/sierra-research/tau-bench@main"
]

train = [
    "torch>=2.7.0",
    "transformers",
    "accelerate>=1.4.0",
    "peft",
    "wandb",
    "rich",
    "trl>=0.17.0",
    "vllm>=0.9.1",
    "liger-kernel>=0.5.10",
    "deepspeed",
]

jupyter = [
    "nest-asyncio>=1.6.0",
    "ipykernel",
    "ipywidgets",
]

envs = [
    "requests",
    "duckduckgo-search",
    "brave-search",
    "reasoning-gym",
    "smolagents>=1.15.0",
    "textarena",
    "nltk",
    "tau-bench @ git+https://github.com/sierra-research/tau-bench@main"
]

docs = [
    "sphinx",
    "myst-parser",
    "sphinx-rtd-theme"
]

tests = [
    "requests",
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.0.0",
]

[project.scripts]
vf-vllm = "verifiers.inference.vllm_server:main"

[tool.setuptools]
packages = ["verifiers"]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "twine>=6.1.0",
]

[project.urls]
Homepage = "https://github.com/willccbb/verifiers"
Documentation = "https://github.com/willccbb/verifiers"
Repository = "https://github.com/willccbb/verifiers.git"
Issues = "https://github.com/willccbb/verifiers/issues"
